### PR TITLE
Extend FileParser to generate directives from an XML sitemap

### PR DESCRIPTION
**Pull request by cahutton**
This implements the enhancement described in #50.

The directives generated are `CheckDirectives` with `follow_redirects` disabled.

### CODE REVIEW

**Comment by bengmur** [comment]
I tested it and it's working well for me. Thanks for doing this!

I think it may be worth updating https://github.com/usnews/smoketest/blob/4edd714/docs/source/features.rst#input-files along with this.

**Comment by cahutton** [comment]
@bengmur: Good call on the documentation, I'll add some info there.

As for the tests, my guess is we need to pin the `lxml` version or stop testing against deprecated/EOLed Python versions.

```console
Collecting lxml (from Smoketest==1.0.0)
  Downloading https://files.pythonhosted.org/packages/e1/f5/5eb3b491958dcfdcfa5daae3c655ab59276bc216ca015e44743c9c220e9e/lxml-4.4.0.tar.gz (4.5MB)
    Complete output from command python setup.py egg_info:
    This lxml version requires Python 2.7, 3.5 or later.
```

According to [the release notes for v4.4.0](https://pypi.org/project/lxml/4.4.0/), support for Python 3.4 was removed sometime around July 27, 2019, which fits with the last passing build ([#12](https://travis-ci.org/usnews/smoketest/builds/476449149)) being in January.

**Comment by cahutton** [comment]
Huzzah!: https://github.com/usnews/smoketest/pull/53

**Comment by bengmur** [comment]
Thank you for adding this functionality and addressing that issue that arose, this looks good!

**Pull request merged**
