### PR TITLE
Set up Travis CI

### LINKED ISSUE #12: Set up and use Travis CI for smoketest
https://travis-ci.org/

Ideally this would include running tests on some set of branches and PRs. Maybe even one of the spiffy badges in the README.

### PR DESCRIPTION
**Pull request by bengmur**
https://travis-ci.org/usnews/smoketest

Closes #12.

### CODE REVIEW

**Comment by bengmur** [comment]
One thing that strikes me as a bit clunky is that we configure Python versions both in `.travis.yml` and `tox.ini`. I think there is a way to get around this by not using the `python` language configuration directive in `.travis.yml` and using the `tox` package rather than `tox-travis`, but I think the benefit of having separate environment reporting/jobs in Travis CI outweighs this.

**Comment by mcbridem** [comment]
This pull request seems reasonable to me.

The little badge in `README.rst` says "build: unknown" currently. I'm not sure if this is intentional or expected. It seems related to "No builds for this repository" at <https://travis-ci.org/usnews/smoketest/builds>. I don't really understand how the tests are getting run without there being a build.

**Comment by bpeebles** [comment]
Oops, I filed this I should comment. This seems good to me. I'm happy with this merging :+1:

**Comment by mcbridem** [comment]
I wonder whether we should explicitly specify branches at some point: <https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches>.

**Comment by bengmur** [comment]
Thanks for the review.

**Pull request merged**
